### ISSUE TITLE
use serverless.yml to deploy the layer won't work

### ISSUE THREAD

**Issue by RukaiYu** [jwerre/node-canvas-lambda#6]
Hi there,

I installed the layer to my lambda function succeed via the AWS console.
While by using the (AWS) serverless yml file to deploy the lambda, it will still get the error.

Do you have any idea?

Thanks
```json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'canvas'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'canvas'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)",
        "    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"
    ]
}
```

Installation sls template sample:
```yml
layers:
  canvasLib:
    path: ../layers/canvas # required, path to layer contents on disk
    name: canvasLibLayer # optional, Deployed Lambda layer name
    description: Layer for canvas # optional, Description to publish to AWS
    compatibleRuntimes:
      - nodejs10.x
  nodeCanvas:
    path: ../layers/nodeCanvas # required, path to layer contents on disk
    name: nodeCanvasLayer # optional, Deployed Lambda layer name
    description: Layer for node-canvas # optional, Description to publish to AWS
    compatibleRuntimes:
      - nodejs10.x
```

```yml
functions:
    layers:
      - { Ref: CanvasLibLambdaLayer }
      - { Ref: NodeCanvasLambdaLayer }
```
